spring.application.name=OpenChapter
spring.data.mongodb.host=cluster0.lplotlh.mongodb.net
spring.data.mongodb.port=
spring.data.mongodb.database=openchapter
spring.data.mongodb.username= 
spring.data.mongodb.password=
spring.data.mongodb.authentication-database=admin